<a href="https://colab.research.google.com/github/Saurabhbiswas16/018_SaurabhBiswas/blob/main/Lab1/Lab_01_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# two matrics
array1 = np.array([[5, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[7, -8]])
print(array1)
print(array2)

[[5 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 7 -8]]


In [ ]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.58775322 0.53728663 0.02453317 0.44211232]
 [0.96239721 0.42627856 0.80047357 0.96327143]
 [0.63680706 0.22524305 0.97483196 0.25487947]]


In [ ]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 81 -33]
 [ 79 -39]]


In [ ]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[81, -33], [79, -39]]


In [ ]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

5.333333333333333


In [ ]:
main_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/CSV/mtcars.csv")

In [ ]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
