<a href="https://colab.research.google.com/github/Saurabhbiswas16/018_SaurabhBiswas/blob/main/Lab5/CE018_LinearRegression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

**Linear Regression Model using PyTorch built-ins**

---


Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
import torch.nn as nn

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [3]:
inputs =  torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

**Dataset and DataLoader**

---


We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [4]:
#define dataset
from torch.utils.data import TensorDataset, DataLoader
dataset = TensorDataset(inputs, targets)
dataset[0:4]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.]]))

In [5]:
# Define data loader
batch_size = 6
dl = DataLoader(dataset, batch_size, shuffle=True)
next(iter(dl))

[tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [ 69.,  96.,  70.],
         [ 91.,  88.,  64.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [ 56.,  70.],
         [119., 133.],
         [103., 119.],
         [ 81., 101.]])]

**nn.Linear**

---


Instead of initializing the weights & biases manually, we can define the model using nn.Linear.

In [6]:
# Define model
model = nn.Linear(3, 2)
print(model.weight, end="\n---------\n")
print(model.bias)

Parameter containing:
tensor([[-0.5267,  0.0623, -0.4535],
        [ 0.1719,  0.4253,  0.1788]], requires_grad=True)
---------
Parameter containing:
tensor([-0.1724, -0.5167], requires_grad=True)


**Optimizer**

---


Instead of manually manipulating the weights & biases using gradients, we can use the optimizer optim.SGD.

In [7]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

**Loss Function**

---


Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [8]:
# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

loss = loss_fn(model(inputs) , targets)
print(loss)

tensor(11172.7627, grad_fn=<MseLossBackward>)


**Train the model**

---


We are ready to train the model now. We can define a utility function fit which trains the model for a given number of epochs.

In [9]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

In [10]:
# Train the model for 100 epochs
fit(100 , model , loss_fn, opt)

# Generate predictions
preds = model(inputs)
print('\n', preds)

Training loss:  tensor(29.8965, grad_fn=<MseLossBackward>)

 tensor([[ 57.9694,  71.2186],
        [ 78.6875,  97.8442],
        [124.1702, 136.9801],
        [ 26.4877,  43.2055],
        [ 92.6995, 110.5754],
        [ 57.9694,  71.2186],
        [ 78.6875,  97.8442],
        [124.1702, 136.9801],
        [ 26.4877,  43.2055],
        [ 92.6995, 110.5754],
        [ 57.9694,  71.2186],
        [ 78.6875,  97.8442],
        [124.1702, 136.9801],
        [ 26.4877,  43.2055],
        [ 92.6995, 110.5754]], grad_fn=<AddmmBackward>)


In [11]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [12]:
fit(100 , model , loss_fn, opt)

Training loss:  tensor(14.6821, grad_fn=<MseLossBackward>)


In [13]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [14]:
# weights and biases
weights = np.random.rand(2, 3)
biases = np.random.rand(15, 2)
print("Weights  :  ", weights, sep='\n')
print("Biases  :  ", biases, sep="\n")

Weights  :  
[[0.81346261 0.0976363  0.91925706]
 [0.99889117 0.68827762 0.56931776]]
Biases  :  
[[0.40210513 0.39977788]
 [0.39194597 0.00175957]
 [0.32677761 0.52859776]
 [0.76279844 0.22023596]
 [0.43177408 0.39759739]
 [0.02226044 0.09444375]
 [0.99091956 0.35455892]
 [0.64653276 0.57368009]
 [0.85402894 0.70853975]
 [0.63562355 0.89198716]
 [0.69531045 0.19294561]
 [0.67610164 0.60437124]
 [0.79061503 0.11236286]
 [0.60154756 0.60069908]
 [0.17467161 0.30085525]]


In [15]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [16]:
# Generate predictions
pred = model(inputs)

# Compare with targets
print("Predictions : ", pred, sep="\n")
print("\nTargets : ", targets, sep="\n")

Predictions : 
[[105.8545615  143.91409779]
 [141.84148996 187.9056236 ]
 [137.49819855 212.68176113]
 [121.94685694 152.76783039]
 [130.28177343 175.24798316]
 [105.47471681 143.60876365]
 [142.44046355 188.25842295]
 [137.81795369 212.72684345]
 [122.03808745 153.25613418]
 [130.48562289 175.74237292]
 [106.14776682 143.70726552]
 [142.12564564 188.50823527]
 [137.96203597 212.26552622]
 [121.78560606 153.14829351]
 [130.02467096 175.15124102]]

Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [17]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [18]:
# Compute loss
loss = mse(pred, targets)
print(loss)

10664.858848915967


In [19]:
# compute gradients
biases_grad = (pred - targets) * 2/x_shape[0]
weights_grad = (np.matmul(np.transpose((pred - targets)), inputs)) * 2/x_shape[0]

print("Weights gradient  :  ",weights_grad, sep="\n")
print("\nBiases gradient  :  ",biases_grad, sep="\n")

Weights gradient  :  
[[ 9162.44893053  7258.43734632  5099.55857049]
 [14388.12890877 13472.12176684  8643.37419028]]

Biases gradient  :  
[[ 6.64727487  9.85521304]
 [ 8.11219866 11.58741648]
 [ 2.46642647 10.62423482]
 [13.32624759 15.43571072]
 [ 3.63756979  7.49973109]
 [ 6.59662891  9.81450182]
 [ 8.19206181 11.63445639]
 [ 2.50906049 10.63024579]
 [13.33841166 15.50081789]
 [ 3.66474972  7.56564972]
 [ 6.68636891  9.8276354 ]
 [ 8.15008608 11.6677647 ]
 [ 2.52827146 10.56873683]
 [13.30474747 15.48643913]
 [ 3.60328946  7.48683214]]


In [20]:
# Adjust weights
weights -= weights_grad * 1e-4
biases -= biases_grad * 1e-4

In [21]:
print("Weights  :  ", weights, sep='\n')
print("\nBiases  :  ", biases, sep="\n")

Weights  :  
[[-0.10278228 -0.62820744  0.40930121]
 [-0.43992172 -0.65893456 -0.29501966]]

Biases  :  
[[4.01440400e-01 3.98792356e-01]
 [3.91134747e-01 6.00827744e-04]
 [3.26530971e-01 5.27535341e-01]
 [7.61465810e-01 2.18692386e-01]
 [4.31410324e-01 3.96847414e-01]
 [2.16007730e-02 9.34622953e-02]
 [9.90100352e-01 3.53395477e-01]
 [6.46281850e-01 5.72617067e-01]
 [8.52695104e-01 7.06989667e-01]
 [6.35257072e-01 8.91230590e-01]
 [6.94641814e-01 1.91962846e-01]
 [6.75286634e-01 6.03204462e-01]
 [7.90362203e-01 1.11305983e-01]
 [6.00217083e-01 5.99150432e-01]
 [1.74311286e-01 3.00106565e-01]]


In [22]:
# Calculate loss
pred = model(inputs)
loss = mse(pred, targets)
print(loss)

59300.26438513408


In [23]:
# repeating same for 200 times
for i in range(200):
    pred = model(inputs)
    loss = mse(pred, targets)
    
    biases_grad = ((((inputs@np.transpose(weights)) + biases) - targets)) * 2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights)) + biases) - targets)), inputs)) * 2/x_shape[0]

    weights -= weights_grad * 1e-4
    biases -= biases_grad * 1e-4

In [24]:
# Calculate loss
pred = model(inputs)
loss = mse(pred, targets)
print(loss)

3.348029970409756e+169


In [25]:
# Print predictions
print(pred)

[[-2.36097090e+84 -4.01500587e+84]
 [-3.10242440e+84 -5.27590245e+84]
 [-3.66635763e+84 -6.23491267e+84]
 [-2.35063814e+84 -3.99743424e+84]
 [-2.97410838e+84 -5.05769156e+84]
 [-2.36097090e+84 -4.01500587e+84]
 [-3.10242440e+84 -5.27590245e+84]
 [-3.66635763e+84 -6.23491267e+84]
 [-2.35063814e+84 -3.99743424e+84]
 [-2.97410838e+84 -5.05769156e+84]
 [-2.36097090e+84 -4.01500587e+84]
 [-3.10242440e+84 -5.27590245e+84]
 [-3.66635763e+84 -6.23491267e+84]
 [-2.35063814e+84 -3.99743424e+84]
 [-2.97410838e+84 -5.05769156e+84]]


In [26]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
